name: finance_dbt
version: "1.0"
config-version: 2

profile: finance_dbt

model-paths: ["dbt/models"]
analysis-paths: ["dbt/analysis"]
test-paths: ["dbt/tests"]
seed-paths: ["dbt/seeds"]
macro-paths: ["dbt/macros"]

models:
  finance_dbt:
    bronze:
      +schema: bronze
      +materialized: incremental

    silver:
      +schema: silver
      +materialized: incremental

    gold:
      +schema: gold
      +materialized: table

    platinum:
      +schema: platinum
      +materialized: table

vars:
  raw_data_path: "data/raw"
